version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: appiersign/nextjs
    env_file:
      - .env
    ports:
      - '3000:3000'
    command:
      - 'yarn'
      - 'start'